name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build -t anandbose16/android-sdk:34.0.0 -t anandbose16/android-sdk:34 -t anandbose16/android-sdk:latest .
    - name: Push the images to Docker hub
      run: docker push anandbose16/android-sdk --all-tags
