name: Build container images of Android SDK

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'
env:
  CMDLINE_VERSION: 11076708
  GRADLE_VERSION: 8.7

jobs:
  build-base:
    runs-on: ubuntu-latest
    name: Build base container image
    permissions: 
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: anandbose16
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: anandbosedev
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build base image
        run: |
          docker build \
          -t anandbose16/android-sdk:base-${{ env.CMDLINE_VERSION }}-${{ env.GRADLE_VERSION }} \
          -t anandbose16/android-sdk:base-latest \
          -t ghcr.io/${{ github.actor }}/android-sdk:base-${{ env.CMDLINE_VERSION }}-${{ env.GRADLE_VERSION }} \
          -t ghcr.io/${{ github.actor }}/android-sdk:base-latest \
          -t quay.io/anandbosedev/android-sdk:base-${{ env.CMDLINE_VERSION }}-${{ env.GRADLE_VERSION }} \
          -t quay.io/anandbosedev/android-sdk:base-latest \
          -f ./android-sdk/base/${{ env.CMDLINE_VERSION }}-${{ env.GRADLE_VERSION }}/Dockerfile \
          ./android-sdk/base/${{ env.CMDLINE_VERSION }}-${{ env.GRADLE_VERSION }}/
      - name: Push base image
        run: |
          docker push anandbose16/android-sdk --all-tags
          docker push ghcr.io/${{ github.actor }}/android-sdk --all-tags
          docker push quay.io/anandbosedev/android-sdk --all-tags
  build-images:
    runs-on: ubuntu-latest
    name: Build Android SDK images
    needs: [ build-base ]
    permissions: 
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - build-tools-version: 34.0.0
            platform-version: 34
            is-latest: true
          - build-tools-version: 33.0.3
            platform-version: 33
          - build-tools-version: 32.0.0
            platform-version: 32
          - build-tools-version: 31.0.0
            platform-version: 31
          - build-tools-version: 30.0.3
            platform-version: 30
          - build-tools-version: 29.0.3
            platform-version: 29
          - build-tools-version: 28.0.3
            platform-version: 28
          - build-tools-version: 27.0.3
            platform-version: 27
          - build-tools-version: 26.0.3
            platform-version: 26
          - build-tools-version: 25.0.3
            platform-version: 25
          - build-tools-version: 24.0.3
            platform-version: 24
          - build-tools-version: 23.0.3
            platform-version: 23
          - build-tools-version: 22.0.1
            platform-version: 22
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: anandbose16
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: anandbosedev
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build Android SDK image ${{ matrix.build-tools-version }}
        run: |
          docker build \
          -t anandbose16/android-sdk:${{ matrix.build-tools-version }} \
          -t anandbose16/android-sdk:${{ matrix.platform-version }} \
          -t ghcr.io/${{ github.actor }}/android-sdk:${{ matrix.build-tools-version }} \
          -t ghcr.io/${{ github.actor }}/android-sdk:${{ matrix.platform-version }} \
          -t quay.io/anandbosedev/android-sdk:${{ matrix.build-tools-version }} \
          -t quay.io/anandbosedev/android-sdk:${{ matrix.platform-version }} \
          -f ./android-sdk/${{ matrix.build-tools-version }}/Dockerfile \
          ./android-sdk/${{ matrix.build-tools-version }}/
      - name: Tag latest
        if: ${{ matrix.is-latest }}
        run: |
          docker tag \
          anandbose16/android-sdk:${{ matrix.build-tools-version }} \
          anandbose16/android-sdk:latest
          docker tag \
          ghcr.io/${{ github.actor }}/android-sdk:${{ matrix.build-tools-version }} \
          ghcr.io/${{ github.actor }}/android-sdk:latest
          docker tag quay.io/anandbosedev/android-sdk:${{ matrix.build-tools-version }} \
          quay.io/anandbosedev/android-sdk:latest
      - name: Push images
        run: |
          docker push anandbose16/android-sdk --all-tags
          docker push ghcr.io/${{ github.actor }}/android-sdk --all-tags
          docker push quay.io/anandbosedev/android-sdk --all-tags